# file: .github/workflows/buildProject.yml
name: buildProject
# on – определяет события, которые запускают воркфлоу
on: 
  - push
  - pull_request
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен, выполняет какую-то задачу
      # checkout – клонирует репозиторий
      
      - uses: actions/checkout@v3
      
      - name: install dependencies
        run: make install
      - name: linter
        run: make lint
      - name: tests
        run: make test
     
      # run – произвольная bash-команда
      # name: имя конкретного run.Важно при присваивании имени '-' 
      # отдается name, следующим за ним run её уже не имеет
      
        